### ISSUE TITLE
60fps and higher not working

### ISSUE THREAD

**Issue by mirkokral** [SM6225-Project/device_motorola_devon#1]
When I use camera2 and set my fps to 60 this happens on open camera.
This is what it looks like:
![Screenshot_20240425-064439~2](https://github.com/SM6225-Project/device_motorola_devon/assets/75212488/94e6f6ef-589a-482d-a3bd-e6722d16991a)

**Comment by KevinFrax** [comment]
@mirkokral Lmaoooooo

**Comment by josexda** [comment]
Be clear

**Comment by ZetLink** [comment]
In 1080p, 30FPS is the max

**Comment by josexda** [comment]
https://www.gsmarena.com/motorola_moto_g32-11733.php

**Comment by mirkokral** [comment]
> In 1080p, 30FPS is the max

i was recording in 720p
